# These are supported funding model platforms
github: # Replace with up to 4 GitHub Sponsors-enabled wuhan2020 e.g., [user1, user2]
github: # Replace with up to 4 GitHub Sponsors-enabled username e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
